sonar.projectKey=PieProton_LexFlow-backend
sonar.organization=pieproton
sonar.host.url=https://sonarcloud.io

sonar.sources=src-tauri/src,client/src
sonar.exclusions=src-tauri/target/**,src-tauri/gen/**,src-tauri/Cargo.lock
